# Generated by Django 3.1.7 on 2021-07-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WaitlistApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=15, unique=True)),
                ('waitlist_t1', models.IntegerField(default=-1, verbose_name='Waitlist Number (Type 1)')),
                ('waitlist_mt', models.IntegerField(default=-1, verbose_name='Waitlist Number (Manas-Tulsi)')),
                ('acad_verified', models.BooleanField(default=False)),
                ('marriage_certificate_verified', models.BooleanField(choices=[(True, 'Verified'), (False, 'Not verified')], default=False, verbose_name='Marriage Certificate')),
                ('photograph_verified', models.BooleanField(choices=[(True, 'Verified'), (False, 'Not verified')], default=False, verbose_name='Photograph')),
                ('grade_sheet_verified', models.BooleanField(choices=[(True, 'Verified'), (False, 'Not verified')], default=False, verbose_name='Grade sheet')),
                ('recommendation_verified', models.BooleanField(choices=[(True, 'Verified'), (False, 'Not verified')], default=False, verbose_name='Recommendations from the guide for accommodation')),
                ('acad_feedback', models.TextField(blank=True, default='', help_text='In case any information provided is invalid.', null=True, verbose_name='Feedback')),
                ('hcu_feedback', models.TextField(blank=True, default='', help_text='In case any information provided is invalid.', null=True, verbose_name='Feedback')),
                ('offer', models.IntegerField(choices=[(0, 'None'), (1, 'Type 1'), (2, 'Manas'), (3, 'Tulsi')], default=0, verbose_name='Shortlisting for')),
                ('occupying', models.IntegerField(choices=[(0, 'None'), (1, 'Type 1'), (2, 'Manas'), (3, 'Tulsi')], default=0)),
                ('vacated', models.IntegerField(choices=[(0, 'None'), (1, 'Type 1'), (2, 'Manas'), (3, 'Tulsi')], default=0)),
                ('offered_on', models.IntegerField(default=0)),
                ('occupied_on', models.DateField(null=True)),
                ('vacated_on', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
