# Generated by Django 3.1.7 on 2021-07-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistapplicant',
            name='offered_on',
            field=models.DateField(null=True),
        ),
    ]
