# Generated by Django 3.1.7 on 2021-07-19 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20210719_0513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tmp',
        ),
    ]
