# Generated by Django 3.1.7 on 2021-07-19 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_delete_tmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistapplicant',
            name='course_work_completed_by',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='waitlistapplicant',
            name='course_work_completes_on',
            field=models.DateField(help_text='Enter the expected date.', null=True),
        ),
        migrations.AddField(
            model_name='waitlistapplicant',
            name='department',
            field=models.CharField(default='', help_text="Example: 'Electrical Engineering'", max_length=128),
        ),
        migrations.AddField(
            model_name='waitlistapplicant',
            name='email',
            field=models.EmailField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='waitlistapplicant',
            name='fellowship',
            field=models.CharField(choices=[('Institute', 'Institute'), ('CSIR', 'CSIR'), ('UGC', 'UGC')], default='', help_text='Select one.', max_length=15),
        ),
        migrations.AddField(
            model_name='waitlistapplicant',
            name='fellowship_date',
            field=models.DateField(null=True, verbose_name='Date from which fellowship is awarded'),
        ),
        migrations.AddField(
            model_name='waitlistapplicant',
            name='grade_sheet',
            field=models.FileField(default='', upload_to='grade_sheets', verbose_name='Coursework grade-sheet'),
        ),
        migrations.AddField(
            model_name='waitlistapplicant',
            name='marriage_certificate',
            field=models.FileField(default='', upload_to='marriage_certificates/'),
        ),
        migrations.AddField(
            model_name='waitlistapplicant',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='waitlistapplicant',
            name='permanent_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='waitlistapplicant',
            name='phone_number',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a 10-digit number without the country code, e.g., 9876543210.', regex='^[0-9]{10}$')]),
        ),
        migrations.AddField(
            model_name='waitlistapplicant',
            name='photograph',
            field=models.FileField(default='', upload_to='photographs', verbose_name='Joint photograph with spouse'),
        ),
        migrations.AddField(
            model_name='waitlistapplicant',
            name='recommendation',
            field=models.FileField(default='', upload_to='recommendations', verbose_name='Recommendation from the guide for accommodation'),
        ),
        migrations.AddField(
            model_name='waitlistapplicant',
            name='spouse_designation',
            field=models.CharField(blank=True, default='', help_text='Leave blank if inapplicable', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='waitlistapplicant',
            name='spouse_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='waitlistapplicant',
            name='spouse_roll_number',
            field=models.CharField(blank=True, default='', help_text='Leave blank if inapplicable', max_length=128, null=True),
        ),
    ]
