# Generated by Django 3.1.7 on 2021-07-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20210719_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='course_work_completed_by',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='course_work_completes_on',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='department',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='fellowship',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='fellowship_date',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='grade_sheet',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='marriage_certificate',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='photograph',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='spouse_designation',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='spouse_name',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='spouse_roll_number',
        ),
    ]
