# Generated by Django 3.1.7 on 2021-07-24 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20210723_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='course_work_completed_by',
        ),
    ]
