# Generated by Django 3.2.5 on 2021-07-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_remove_waitlistapplicant_course_work_completed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='course_work_completes_on',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='department',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='fellowship',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='fellowship_date',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='grade_sheet',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='marriage_certificate',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='photograph',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='spouse_designation',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='spouse_name',
        ),
        migrations.RemoveField(
            model_name='waitlistapplicant',
            name='spouse_roll_number',
        ),
        migrations.AddField(
            model_name='waitlistapplicant',
            name='form_updated',
            field=models.BooleanField(default=False),
        ),
    ]
