# Generated by Django 3.2.5 on 2021-07-28 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20210728_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistapplicant',
            name='grade_sheet',
            field=models.FileField(default='', help_text='PDF only', upload_to='grade_sheets', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Coursework grade-sheet'),
        ),
        migrations.AddField(
            model_name='waitlistapplicant',
            name='marriage_certificate',
            field=models.FileField(default='', help_text='PDF only', upload_to='marriage_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='waitlistapplicant',
            name='photograph',
            field=models.FileField(default='', help_text='PDF only', upload_to='photographs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Joint photograph with spouse'),
        ),
        migrations.AddField(
            model_name='waitlistapplicant',
            name='recommendation',
            field=models.FileField(default='', help_text='PDF only', upload_to='recommendations', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Recommendation from the guide for accommodation'),
        ),
    ]
