# Generated by Django 3.2.5 on 2021-07-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20210728_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistapplicant',
            name='updated_form',
            field=models.BooleanField(default=True),
        ),
    ]
